# Generated by Django 6.0.5 on 2026-05-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('employe', 'Employé'), ('manager', 'Manager'), ('rh', 'RH'), ('admin', 'Admin')], max_length=10, null=True),
        ),
    ]
