# Generated by Django 6.0.5 on 2026-06-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
