# Generated by Django 6.0.5 on 2026-05-12 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=255)),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
            },
        ),
        migrations.CreateModel(
            name='SoldesConges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_jours', models.PositiveIntegerField(default=30)),
                ('jours_utilise', models.PositiveIntegerField(default=0)),
                ('jours_restant', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solde des conges',
                'verbose_name_plural': 'Solde des conges',
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('accepte', 'Accepté'), ('refuse', 'Refusé')], max_length=10)),
                ('commentaire', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Validation',
                'verbose_name_plural': 'Validations',
            },
        ),
        migrations.CreateModel(
            name='Conges',
            fields=[
                ('demande_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demande.demande')),
                ('date_debut', models.DateField()),
                ('nombre_jours', models.PositiveIntegerField()),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conge',
                'verbose_name_plural': 'conges',
            },
            bases=('demande.demande',),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('demande_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demande.demande')),
                ('motif', models.TextField()),
                ('heure_sortie', models.DateTimeField()),
                ('nombre_minute', models.PositiveIntegerField()),
                ('heure_retour', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
            bases=('demande.demande',),
        ),
        migrations.CreateModel(
            name='ReposMaladie',
            fields=[
                ('demande_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demande.demande')),
                ('date_debut', models.DateField()),
                ('nombre_jours', models.PositiveIntegerField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('justificatif', models.FileField(upload_to='justificatifs/')),
            ],
            options={
                'verbose_name': 'Repos Maladie',
                'verbose_name_plural': 'Repos maladies',
            },
            bases=('demande.demande',),
        ),
    ]
