# Generated by Django 6.0.5 on 2026-05-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=255)),
                ('date_debut', models.DateField()),
                ('nombre_jours', models.PositiveIntegerField()),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conge',
                'verbose_name_plural': 'conges',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=255)),
                ('motif', models.TextField()),
                ('heure_sortie', models.DateTimeField()),
                ('nombre_minute', models.PositiveIntegerField()),
                ('heure_retour', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='ReposMaladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=255)),
                ('date_debut', models.DateField()),
                ('nombre_jours', models.PositiveIntegerField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('justificatif', models.FileField(upload_to='justificatifs/')),
            ],
            options={
                'verbose_name': 'Repos Maladie',
                'verbose_name_plural': 'Repos maladies',
            },
        ),
        migrations.CreateModel(
            name='SoldesConges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_jours', models.PositiveIntegerField(default=30)),
                ('jours_utilise', models.PositiveIntegerField(default=0)),
                ('jours_restant', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solde des conges',
                'verbose_name_plural': 'Solde des conges',
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('type_demande', models.CharField(choices=[('permission', 'Permission'), ('conge', 'Congé'), ('repos_maladie', 'Repos maladie')], max_length=255)),
                ('demande_id', models.PositiveIntegerField()),
                ('decision', models.CharField(choices=[('accepte', 'Accepté'), ('refuse', 'Refusé')], max_length=10)),
                ('commentaire', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Validation',
                'verbose_name_plural': 'Validations',
            },
        ),
    ]
