# Generated by Django 6.0.5 on 2026-05-13 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demande', '0001_initial'),
        ('employe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conges',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.employe'),
        ),
        migrations.AddField(
            model_name='permission',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.employe'),
        ),
        migrations.AddField(
            model_name='reposmaladie',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.employe'),
        ),
        migrations.AddField(
            model_name='soldesconges',
            name='employe_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solde_conge', to='employe.employe'),
        ),
        migrations.AddField(
            model_name='validation',
            name='validateur_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_effectuees', to=settings.AUTH_USER_MODEL),
        ),
    ]
