# Generated by Django 6.0.5 on 2026-05-12 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demande', '0001_initial'),
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.employe'),
        ),
        migrations.AddField(
            model_name='soldesconges',
            name='employe_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solde_conge', to='employe.employe'),
        ),
        migrations.AddField(
            model_name='validation',
            name='demande_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='demande.demande'),
        ),
        migrations.AddField(
            model_name='validation',
            name='validateur_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_effectuees', to='employe.employe'),
        ),
    ]
