# Generated by Django 6.0.5 on 2026-05-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validation',
            old_name='validateur_id',
            new_name='validateur',
        ),
    ]
