# Generated by Django 6.0.5 on 2026-06-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0003_rename_validateur_id_validation_validateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conges',
            name='statut',
            field=models.CharField(choices=[('en attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en attente', max_length=255),
        ),
        migrations.AlterField(
            model_name='permission',
            name='statut',
            field=models.CharField(choices=[('en attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en attente', max_length=255),
        ),
        migrations.AlterField(
            model_name='reposmaladie',
            name='statut',
            field=models.CharField(choices=[('en attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en attente', max_length=255),
        ),
    ]
