# Generated by Django 6.0.5 on 2026-06-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0004_alter_conges_statut_alter_permission_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='heure_retour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='heure_sortie',
            field=models.TimeField(),
        ),
    ]
