# Generated by Django 6.0.5 on 2026-06-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0005_alter_permission_heure_retour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldesconges',
            old_name='employe_id',
            new_name='employe',
        ),
    ]
