# Generated by Django 6.0.5 on 2026-07-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0006_rename_employe_id_soldesconges_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='commentaire',
            field=models.CharField(default='', max_length=255),
        ),
    ]
