# Generated by Django 6.0.5 on 2026-07-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0007_alter_validation_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='conges',
            name='confirme',
            field=models.BooleanField(default=False),
        ),
    ]
