# Generated by Django 6.0.5 on 2026-07-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0008_conges_confirme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conges',
            old_name='confirme',
            new_name='traite',
        ),
    ]
