# Generated by Django 6.0.5 on 2026-09-16 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0009_rename_confirme_conges_traite'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Type de congé',
                'verbose_name_plural': 'Types de congés',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Type de permission',
                'verbose_name_plural': 'Types de permissions',
                'ordering': ['libelle'],
            },
        ),
        migrations.AddField(
            model_name='conges',
            name='type_conge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conges', to='demande.typeconge'),
        ),
        migrations.AddField(
            model_name='permission',
            name='type_permission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='demande.typepermission'),
            preserve_default=False,
        ),
    ]
