# Generated by Django 6.0.5 on 2026-09-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0010_typeconge_typepermission_conges_type_conge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='heure_retour',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='heure_sortie',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='nombre_minute',
        ),
        migrations.AddField(
            model_name='permission',
            name='date_permission',
            field=models.DateField(null=True),
        ),
    ]
