# Generated by Django 6.0.5 on 2026-09-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0011_remove_permission_heure_retour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='date_retour',
            field=models.DateField(null=True),
        ),
    ]
