# Generated by Django 6.0.5 on 2026-09-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0012_permission_date_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='motif',
            field=models.TextField(null=True),
        ),
    ]
