# Generated by Django 6.0.5 on 2026-09-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0014_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='demande',
            new_name='demande_id',
        ),
    ]
